/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ChildTokenContract } from "./ChildToken";
import { DRCChildERC20Contract } from "./DRCChildERC20";
import { ERC20Contract } from "./ERC20";
import { IERC20Contract } from "./IERC20";
import { IParentTokenContract } from "./IParentToken";
import { LibEIP712DomainContract } from "./LibEIP712Domain";
import { LibTokenTransferOrderContract } from "./LibTokenTransferOrder";
import { MigrationsContract } from "./Migrations";
import { OwnableContract } from "./Ownable";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ChildToken"): ChildTokenContract;
      require(name: "DRCChildERC20"): DRCChildERC20Contract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IParentToken"): IParentTokenContract;
      require(name: "LibEIP712Domain"): LibEIP712DomainContract;
      require(name: "LibTokenTransferOrder"): LibTokenTransferOrderContract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Ownable"): OwnableContract;
    }
  }
}

export { ChildTokenContract, ChildTokenInstance } from "./ChildToken";
export { DRCChildERC20Contract, DRCChildERC20Instance } from "./DRCChildERC20";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export { IParentTokenContract, IParentTokenInstance } from "./IParentToken";
export {
  LibEIP712DomainContract,
  LibEIP712DomainInstance,
} from "./LibEIP712Domain";
export {
  LibTokenTransferOrderContract,
  LibTokenTransferOrderInstance,
} from "./LibTokenTransferOrder";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { OwnableContract, OwnableInstance } from "./Ownable";
