/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { DigitalReserveContract } from "./DigitalReserve";
import { ERC20Contract } from "./ERC20";
import { IDigitalReserveContract } from "./IDigitalReserve";
import { IERC20Contract } from "./IERC20";
import { IUniswapV2Router01Contract } from "./IUniswapV2Router01";
import { IUniswapV2Router02Contract } from "./IUniswapV2Router02";
import { MigrationsContract } from "./Migrations";
import { OwnableContract } from "./Ownable";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "DigitalReserve"): DigitalReserveContract;
      require(name: "ERC20"): ERC20Contract;
      require(name: "IDigitalReserve"): IDigitalReserveContract;
      require(name: "IERC20"): IERC20Contract;
      require(name: "IUniswapV2Router01"): IUniswapV2Router01Contract;
      require(name: "IUniswapV2Router02"): IUniswapV2Router02Contract;
      require(name: "Migrations"): MigrationsContract;
      require(name: "Ownable"): OwnableContract;
    }
  }
}

export {
  DigitalReserveContract,
  DigitalReserveInstance,
} from "./DigitalReserve";
export { ERC20Contract, ERC20Instance } from "./ERC20";
export {
  IDigitalReserveContract,
  IDigitalReserveInstance,
} from "./IDigitalReserve";
export { IERC20Contract, IERC20Instance } from "./IERC20";
export {
  IUniswapV2Router01Contract,
  IUniswapV2Router01Instance,
} from "./IUniswapV2Router01";
export {
  IUniswapV2Router02Contract,
  IUniswapV2Router02Instance,
} from "./IUniswapV2Router02";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
export { OwnableContract, OwnableInstance } from "./Ownable";
