/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventData, PastEventOptions } from "web3-eth-contract";

export interface LibTokenTransferOrderContract
  extends Truffle.Contract<LibTokenTransferOrderInstance> {
  "new"(
    meta?: Truffle.TransactionDetails
  ): Promise<LibTokenTransferOrderInstance>;
}

type AllEvents = never;

export interface LibTokenTransferOrderInstance
  extends Truffle.ContractInstance {
  EIP712_DOMAIN_HASH(txDetails?: Truffle.TransactionDetails): Promise<string>;

  EIP712_DOMAIN_SCHEMA_HASH(
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  EIP712_TOKEN_TRANSFER_ORDER_SCHEMA_HASH(
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  getTokenTransferOrderHash(
    spender: string,
    tokenIdOrAmount: number | BN | string,
    data: string,
    expiration: number | BN | string,
    txDetails?: Truffle.TransactionDetails
  ): Promise<string>;

  methods: {
    EIP712_DOMAIN_HASH(txDetails?: Truffle.TransactionDetails): Promise<string>;

    EIP712_DOMAIN_SCHEMA_HASH(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    EIP712_TOKEN_TRANSFER_ORDER_SCHEMA_HASH(
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;

    getTokenTransferOrderHash(
      spender: string,
      tokenIdOrAmount: number | BN | string,
      data: string,
      expiration: number | BN | string,
      txDetails?: Truffle.TransactionDetails
    ): Promise<string>;
  };

  getPastEvents(event: string): Promise<EventData[]>;
  getPastEvents(
    event: string,
    options: PastEventOptions,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
  getPastEvents(event: string, options: PastEventOptions): Promise<EventData[]>;
  getPastEvents(
    event: string,
    callback: (error: Error, event: EventData) => void
  ): Promise<EventData[]>;
}
